### ISSUE TITLE
TS Issue: Introduced in 1.2.2

### ISSUE THREAD

**Issue by funwithtriangles** [charkour/zundo#21]
This is a strange one because v1.2.2 doesn't seem to have many changes, but in my project, I have no type errors when using 1.2.1, when I upgrade to 1.2.2 (or higher) I'm getting the below error when trying to use the store. 

```
src/store/index.ts:197:32 - error TS2345: Argument of type '(set: SetState<Partial<Pick<UndoStoreState, "undo" | "redo" | "clear"> & { getState: () => UndoStoreState; }>>, get: GetState<...>, api: StoreApi<...>) => Partial<...>' is not assignable to parameter of type 'StateCreator<Store, SetState<Store>> | StoreApi<Store>'.
  Type '(set: SetState<Partial<Pick<UndoStoreState, "undo" | "redo" | "clear"> & { getState: () => UndoStoreState; }>>, get: GetState<...>, api: StoreApi<...>) => Partial<...>' is not assignable to type 'StateCreator<Store, SetState<Store>>'.
    Types of parameters 'set' and 'set' are incompatible.
      Types of parameters 'partial' and 'partial' are incompatible.
        Type 'PartialState<Partial<Pick<UndoStoreState, "undo" | "redo" | "clear"> & { getState: () => UndoStoreState; }>, K1, K2, K3, K4>' is not assignable to type 'PartialState<Store, K1, K2, K3, K4>'.
          Type 'Partial<Pick<UndoStoreState, "undo" | "redo" | "clear"> & { getState: () => UndoStoreState; }>' is not assignable to type 'PartialState<Store, K1, K2, K3, K4>'.
            Type 'Partial<Pick<UndoStoreState, "undo" | "redo" | "clear"> & { getState: () => UndoStoreState; }>' is missing the following properties from type 'Store': addCameraAngle, setBatchId, setWizardText, setDidCatchError, and 81 more.
```

For now the easiest fix is just to use a `@ts-ignore`:

```
// @ts-ignore
const useStore = create<Store>(store)
```

**Comment by charkour** [comment]
I hope to fix this in v2

**Comment by charkour** [comment]
Nearing the end of v2. Won't be fixing this issue. 

The types for v2 are much better. Sorry for the hassle!
